{% set version = "1.1" %}

package:
    name: cmocean
    version: {{ version }}

source:
    fn: cmocean-{{ version }}.tar.gz
    url: https://github.com/matplotlib/cmocean/archive/{{ version }}.tar.gz
    sha256: ccc5aa3e277f7f163ac58a2670326f48310ec5154b1c85d4fb1069d623fdfa20

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - matplotlib

test:
    imports:
        - cmocean
    requires:
        - pytest

about:
    home: https://github.com/matplotlib/cmocean
    license: MIT
    summary: 'Colormaps for Oceanography'

extra:
    recipe-maintainers:
        - ocefpaf
