{% set version = "3.0.3" %}

package:
  name: cmocean
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cmocean/cmocean-{{ version }}.tar.gz
  sha256: abaf99383c1a60f52970c86052ae6c14eafa84fc16984488040283c02db77c0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    # colorspacious is imported directly, not a soft optional dep
    - colorspacious

test:
  imports:
    - cmocean

about:
  home: https://github.com/matplotlib/cmocean
  license: MIT
  license_file: LICENSE.txt
  summary: Colormaps for Oceanography

extra:
  recipe-maintainers:
    - kthyng
    - ocefpaf
