{% set version = "1.0" %}

package:
    name: cmocean
    version: {{ version }}

source:
    fn: cmocean-{{ version }}.tar.gz
    url: https://github.com/matplotlib/cmocean/archive/{{ version }}.tar.gz
    sha256: 7f52753cd7cb2a8ccd532dadbce8db149088e27e3ad9b9f05ec9a30b6c12db4c

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - matplotlib

test:
    imports:
        - cmocean
    requires:
        - pytest

about:
    home: https://github.com/matplotlib/cmocean
    license: MIT
    summary: 'Colormaps for Oceanography'

extra:
    recipe-maintainers:
        - ocefpaf
