{% set name = "cmocean" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmocean-{{ version }}.tar.gz
  sha256: 37868399fb5f41b4eac596e69803f9bfaea49946514dfb2e7f48886854250d7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - numpy
    - packaging
    # colorspacious is imported directly, not a soft optional dep
    - colorspacious

test:
  imports:
    - cmocean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matplotlib/cmocean
  license: MIT
  license_file: LICENSE.txt
  summary: Colormaps for Oceanography

extra:
  recipe-maintainers:
    - kthyng
    - ocefpaf
